name: Covid19-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.26.4
  - pandas>=2.2.2
  - matplotlib>=3.10.0
  - seaborn>=0.13.2
  - scikit-learn>=1.2.2
  - jupyter
  - ipykernel
  - pip
  - pip:
    - "tensorflow[and-cuda]>=2.15.0"
    - opencv-python>=4.11.0.86

